
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DEVICE DEVICES EDIT EXIT HOME MOVE NUMBER OFF ON PARAMETER REMOVE RESERVED ROOM ROOMS STATUS TIMERexpression : STATUSexpression : EXITexpression : ROOMSexpression : ROOM PARAMETER STATUSexpression : ROOM PARAMETER STATUS PARAMETERexpression : ADD DEVICE PARAMETER PARAMETERexpression : REMOVE DEVICE PARAMETER PARAMETERexpression : REMOVE ROOM PARAMETERexpression : ADD ROOM PARAMETERexpression : ROOM PARAMETER DEVICES'
    
_lr_action_items = {'STATUS':([0,8,],[2,13,]),'EXIT':([0,],[3,]),'ROOMS':([0,],[4,]),'ROOM':([0,6,7,],[5,10,12,]),'ADD':([0,],[6,]),'REMOVE':([0,],[7,]),'$end':([1,2,3,4,13,14,16,18,19,20,21,],[0,-1,-2,-3,-4,-10,-9,-8,-5,-6,-7,]),'PARAMETER':([5,9,10,11,12,13,15,17,],[8,15,16,17,18,19,20,21,]),'DEVICE':([6,7,],[9,11,]),'DEVICES':([8,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> STATUS','expression',1,'p_STATUS','homeYacc.py',10),
  ('expression -> EXIT','expression',1,'p_EXIT','homeYacc.py',20),
  ('expression -> ROOMS','expression',1,'p_ROOMS','homeYacc.py',27),
  ('expression -> ROOM PARAMETER STATUS','expression',3,'p_print_room_status_devices','homeYacc.py',33),
  ('expression -> ROOM PARAMETER STATUS PARAMETER','expression',4,'p_print_room_status_device','homeYacc.py',36),
  ('expression -> ADD DEVICE PARAMETER PARAMETER','expression',4,'p_add_device','homeYacc.py',39),
  ('expression -> REMOVE DEVICE PARAMETER PARAMETER','expression',4,'p_remove_device','homeYacc.py',43),
  ('expression -> REMOVE ROOM PARAMETER','expression',3,'p_remove_room','homeYacc.py',46),
  ('expression -> ADD ROOM PARAMETER','expression',3,'p_add_room','homeYacc.py',50),
  ('expression -> ROOM PARAMETER DEVICES','expression',3,'p_print_room_devices','homeYacc.py',57),
]
